# ATO Cycle Schedule Configuration
#
# Defines the 72-hour ATO cycle phases, timing, and agent assignments

ato_cycle:
  total_duration_hours: 72
  phases:
    - phase_id: PHASE1_OEG
      name: "Objectives, Effects, Guidance (OEG)"
      duration_hours: 6
      offset_hours: 0
      active_agents:
        - ems_strategy_agent
      key_outputs:
        - ems_strategy
        - commander_guidance
      critical: false
      description: "Develop EMS strategy from JFACC guidance"

    - phase_id: PHASE2_TARGET_DEVELOPMENT
      name: "Target Development"
      duration_hours: 8
      offset_hours: 6
      active_agents:
        - ems_strategy_agent
      key_outputs:
        - target_list
        - ems_requirements
      critical: false
      description: "Identify targets and EMS requirements"

    - phase_id: PHASE3_WEAPONEERING
      name: "Weaponeering & Allocation"
      duration_hours: 10
      offset_hours: 14
      active_agents:
        - ew_planner_agent
        - spectrum_manager_agent
      key_outputs:
        - ew_missions
        - frequency_allocations
      critical: true
      description: "Plan EW missions and allocate spectrum"

    - phase_id: PHASE4_ATO_PRODUCTION
      name: "ATO Production"
      duration_hours: 6
      offset_hours: 24
      active_agents:
        - ato_producer_agent
        - spectrum_manager_agent
      key_outputs:
        - ato_document
        - spins_annex
      critical: true
      description: "Produce ATO with EMS annex"

    - phase_id: PHASE5_EXECUTION
      name: "Execution"
      duration_hours: 24
      offset_hours: 30
      active_agents:
        - spectrum_manager_agent
      key_outputs:
        - execution_data
        - real_time_adjustments
      critical: false
      description: "Execute ATO with real-time spectrum management"

    - phase_id: PHASE6_ASSESSMENT
      name: "Assessment"
      duration_hours: 18
      offset_hours: 54
      active_agents:
        - assessment_agent
      key_outputs:
        - effectiveness_assessment
        - lessons_learned
      critical: false
      description: "Assess effectiveness and generate lessons learned"

# Phase transition rules
phase_transitions:
  allow_skip: false  # Phases cannot be skipped
  allow_rollback: false  # Cannot go back to previous phase
  critical_phase_alert: true  # Alert on critical phase start

# Timing thresholds for process improvement
timing_thresholds:
  warning_multiplier: 1.3  # Flag if >30% over expected time
  critical_multiplier: 1.5  # Critical flag if >50% over expected time
  efficiency_target: 0.9    # Target 90% efficiency
